### ISSUE TITLE
Wrap JSON.parse() in a try catch and return null if failed

### ISSUE THREAD

**Issue by nodeful** [PotentialWeb/Prebid.js#3]
https://github.com/PotentialWeb/Prebid.js/blob/9e28ba4648a1b6a34468d94e5de0ccec01dbdd36/modules/37xAnalyticsAdapter.js#L440

**Comment by willviles** [comment]
Commit updated with:

https://github.com/PotentialWeb/Prebid.js/blob/37x-analytics-adapter/modules/37xAnalyticsAdapter.js#L440-L445
